/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CTASection: typeof import('./components/sections/CTASection.vue')['default']
    FeaturePanels: typeof import('./components/sections/FeaturePanels.vue')['default']
    FlowingLogos: typeof import('./components/FlowingLogos.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/sections/HeroSection.vue')['default']
    LanguageExpert: typeof import('./components/sections/LanguageExpert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollFade: typeof import('./components/ScrollFade.vue')['default']
    Sect: typeof import('./components/sections/Sect.vue')['default']
    StickyShowcase: typeof import('./components/sections/StickyShowcase.vue')['default']
    ToonCard: typeof import('./components/ToonCard.vue')['default']
    ToonCardEx: typeof import('./components/ToonCardEx.vue')['default']
    ToonCardRow: typeof import('./components/ToonCardRow.vue')['default']
    VideoSection: typeof import('./components/sections/VideoSection.vue')['default']
  }
}
