/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDeveloper: typeof import('./components/sections/AppDeveloper.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DevOpsEngineer: typeof import('./components/sections/DevOpsEngineer.vue')['default']
    FeaturePanels: typeof import('./components/sections/FeaturePanels.vue')['default']
    FindMeOn: typeof import('./components/sections/FindMeOn.vue')['default']
    FlowingLogos: typeof import('./components/FlowingLogos.vue')['default']
    GameDeveloperTitle: typeof import('./components/GameDeveloperTitle.vue')['default']
    GameDeveolper: typeof import('./components/sections/GameDeveolper.vue')['default']
    GraphicsEngineer: typeof import('./components/sections/GraphicsEngineer.vue')['default']
    Introduction: typeof import('./components/sections/Introduction.vue')['default']
    LanguageExpert: typeof import('./components/sections/LanguageExpert.vue')['default']
    MyCard: typeof import('./components/MyCard.vue')['default']
    MyCardEx: typeof import('./components/MyCardEx.vue')['default']
    MyCardParagraph: typeof import('./components/MyCardParagraph.vue')['default']
    MyCardTable: typeof import('./components/MyCardTable.vue')['default']
    OneLiner: typeof import('./components/OneLiner.vue')['default']
    Person: typeof import('./components/sections/Person.vue')['default']
    ProgrammingLanguageExpertTitle: typeof import('./components/ProgrammingLanguageExpertTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollFade: typeof import('./components/ScrollFade.vue')['default']
    Sect: typeof import('./components/sections/Sect.vue')['default']
    SlidingLogoBanner: typeof import('./components/SlidingLogoBanner.vue')['default']
    StickyShowcase: typeof import('./components/sections/StickyShowcase.vue')['default']
    VideoSection: typeof import('./components/sections/VideoSection.vue')['default']
  }
}
